### ISSUE TITLE
Add base rules

### ISSUE THREAD

**Issue by azinit** [martis-git/actool-cli#18]
- [x] Ural
- [x] Ilya
- [x] Damir

**Comment by azinit** [comment]
Damir:
```
comment-lines:
  types: ["multiple", "oneline"] // то бишь [/**/, //]

function-body-actual-state:
  part: 95 //считаем по алгоритму схожесть текста [70-95]

warnings-notification-per-time:
  every:  ["commit", "save"] // сообщения о том, что мб нужно изменить комент - перед каждым комитом, сохранением

comment-expired-time:
  days: [null, number]
```
